version: "3.8"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - music-network
  postgres_sql:
    image: postgres
    networks:
      - music-network
networks:
  music-network:
    driver: bridge